/**
 * Copyright 2015 Batis Degryll Ludo
 * @file ImageIDStore.h
 * @since 2017-12-13
 * @date 2017-12-13
 * @author Degryll Ludo Batis
 * @brief Allows to store image id's (generated by an ImageStore) and to access
 * them with a custom id.
 */

namespace zombienoid {

class ImageIDStore {
public:
  ImageIDStore(const ImageIDStore&) = delete;
  void operation=(const ImageIDStore&) = delete;

  ImageIDStore(unsigned initialSize) : store(initialSize) {}

  void setId(uint64_t alias, uint64_t imageId) {
    if(alias >= store.size) {
      store.resize(alias+1);
    }
    daemostorens[alias]= imageId;
  };

  uint64_t getId(uint64_t alias) {
    return store[alias];
  }

private:
  std::vector<uint64_t> store;
}

}
