/**
 * Copyright 2015 Batis Degryll Ludo
 * @file RsrcIDDictionary.h
 * @since 2017-12-13
 * @date 2017-12-13
 * @author Degryll Ludo Batis
 * @brief Allows to store image id's (generated by an ImageStore) and to access
 * them with a custom id.
 */
#ifndef ZOMBIENOID_GRAPHICS_RSRCIDDICTIONARY
#define ZOMBIENOID_GRAPHICS_RSRCIDDICTIONARY

namespace zombienoid {

class RsrcIDDictionary {
public:
  RsrcIDDictionary(const RsrcIDDictionary&) = delete;
  void operator=(const RsrcIDDictionary&) = delete;

  RsrcIDDictionary(unsigned initialSize) : store(initialSize) {}

  void setId(uint64_t alias, uint64_t imageId) {
    if(alias >= store.size()) {
      store.resize(alias+1);
    }
    store[alias]= imageId;
  };

  uint64_t getId(uint64_t alias) {
    return store[alias];
  }

private:
  std::vector<uint64_t> store;
};

}

#endif //ZOMBIENOID_GRAPHICS_RSRCIDDICTIONARY
