# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container || '' }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-22.04
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-22.04
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4
    - name: Install deps ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build libfreetype-dev mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev

    - name: switch to gcc-11 on linux
      if: contains(matrix.c_compiler, 'gcc')
      run: |
        sudo apt install gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
        sudo update-alternatives --set gcc /usr/bin/gcc-11  

    - name: Switch to clang-11
      if: matrix.c_compiler == 'clang'
      run: |
        sudo apt-get install -y clang-11
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-11 100 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-11
        sudo update-alternatives --set clang /usr/bin/clang-11

    - name: Set up MSVC environment
      if: contains(matrix.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1
        
    - name: Instalar libpng and zlib through vcpkg
      if: contains(matrix.os, 'windows')
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install libpng
        
    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: create directory
      run: |
        mkdir build

    - name: Configure CMake GCC
      if: contains(matrix.c_compiler, 'gcc')
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ./build 
        -S . 
        -G Ninja 
        -DCMAKE_CXX_COMPILER=/usr/bin/g++ 
        -DCMAKE_C_COMPILER=/usr/bin/gcc 
        -DCMAKE_BUILD_TYPE=Release 
        -DCMAKE_CXX_STANDARD=20 
        -DZBE_ENABLE_CPPCHECK:BOOL="0" 
        -DZBE_BUILD_FUZZ_TESTS:BOOL="0" 
        -DZBE_ENABLE_SANITIZER_UNDEFINED:BOOL="0" 
        -DZBE_ENABLE_SANITIZER_ADDRESS:BOOL="0"

    - name: Configure CMake Clang
      if: contains(matrix.c_compiler, 'clang')
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ./build 
        -S . 
        -G Ninja 
        -DCMAKE_CXX_COMPILER=/usr/bin/clang++
        -DCMAKE_C_COMPILER=/usr/bin/clang
        -DCMAKE_BUILD_TYPE=Release 
        -DCMAKE_CXX_STANDARD=20 
        -DZBE_ENABLE_CPPCHECK:BOOL="0" 
        -DZBE_BUILD_FUZZ_TESTS:BOOL="0" 
        -DZBE_ENABLE_SANITIZER_UNDEFINED:BOOL="0" 
        -DZBE_ENABLE_SANITIZER_ADDRESS:BOOL="0"

    - name: Configure CMake windows
      if: contains(matrix.os, 'windows')
      shell: powershell
      # run: cmake -DCMAKE_TOOLCHAIN_FILE=D:/a/ZBE/ZBE/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DZBE_ENABLE_CPPCHECK:BOOL="0" -DZBE_BUILD_FUZZ_TESTS:BOOL="0" -DZBE_ENABLE_SANITIZER_UNDEFINED:BOOL="0" -DZBE_ENABLE_SANITIZER_ADDRESS:BOOL="0"
      run: |
        cmake `
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake `
          -DVCPKG_TARGET_TRIPLET=x64-windows `
          -S . -B ./build -G Ninja `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_CXX_STANDARD=20 `
          -DZBE_ENABLE_CPPCHECK:BOOL="0" `
          -DZBE_BUILD_FUZZ_TESTS:BOOL="0" `
          -DZBE_ENABLE_SANITIZER_UNDEFINED:BOOL="0" `
          -DZBE_ENABLE_SANITIZER_ADDRESS:BOOL="0"



    # # - name: Copy pnglibconf.h
    # #   if: contains(matrix.os, 'windows')
    # #   run: copy build\_deps\libpng-src\scripts\pnglibconf.h.prebuilt build\_deps\libpng-src\pnglibconf.h
    # #   shell: cmd

    # - name: Download GLEW
    #   if: contains(matrix.os, 'windows')
    #   run: |
    #     curl -L -o glew.zip https://sourceforge.net/projects/glew/files/glew/2.2.0/glew-2.2.0.zip/download
    #     unzip glew.zip

    # - name: Build GLEW (static, /MD)
    #   if: contains(matrix.os, 'windows')
    #   run: |
    #     cd glew-2.2.0
    #     mkdir build_cmake
    #     cd build_cmake
    #     cmake -G "Ninja" -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC=ON -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL ../build/cmake
    #     cmake --build . --config Release

    # - name: List GLEW build output
    #   if: contains(matrix.os, 'windows')
    #   shell: bash
    #   run: |
    #     echo 'Listing build_cmake:'
    #     ls -lR glew-2.2.0/build_cmake
    #     echo 'Listing build_cmake/lib:'
    #     ls -l glew-2.2.0/build_cmake/lib

    # - name: Copy GLEW static lib to extlibs
    #   if: contains(matrix.os, 'windows')
    #   shell: bash
    #   run: |
    #     mkdir -p ${{ github.workspace }}/extlibs/glew/2.2.0/windows/x64/
    #     cp glew-2.2.0/build_cmake/lib/glew32.lib ${{ github.workspace }}/extlibs/glew/2.2.0/windows/x64/glew32s.lib
    #     cp -r glew-2.2.0/include/GL ${{ github.workspace }}/extlibs/glew/2.2.0/include/

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
      run: |
       cd build
       ninja -v

    # - name: Test
    # TODO
    #   working-directory: ${{ steps.strings.outputs.build-output-dir }}
    #   # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
    #   # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #   run: ctest --build-config ${{ matrix.build_type }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}-${{ matrix.cpp_compiler }}
        path: build
